mode:
  develop: true
server:
  port: 3939
log:
  # 1MB
  MaxSize: 1
  # 最大存在文件数
  MaxBackups: 10
  # 最长保留天数
  MaxAge: 90
db:
  dsn: root:123456@tcp(127.0.0.1:3306)/gofly?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 10
  maxOpenConns: 20
redis:
  dsn: localhost:6379